import type {GetStaticProps, NextPage} from 'next'
import Head from 'next/head'
import Header from "../src/Header";
import {Button, Container, Step, StepContent, StepLabel, Stepper} from "@mui/material";
import {useState} from "react";
import {Type} from "../data/types";
import TypeChoiceTab from "../src/TypeChoiceTab";

export const getStaticProps: GetStaticProps = async (context) => {
    const res = await fetch("http://localhost:3000/api/types")
    const data = await res.json()
    return {
        props: {
            types: data
        }
    }
}

type Props = {types: Type[]}

const Home: NextPage<Props> = (props: Props) => {
    const [step, setStep] = useState(0)
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <Container>
                <Stepper orientation="vertical" activeStep={step}>
                    <Step>
                        <StepLabel>Выберите тип</StepLabel>
                        <StepContent>
                            <TypeChoiceTab types={props.types}/>
                            <Button onClick={() => setStep(1)}>Continue</Button>
                        </StepContent>
                    </Step>
                    <Step>
                        <StepLabel>Введите данные</StepLabel>
                        <StepContent><Button onClick={() => setStep(0)}>Back</Button>{"BRUH ".repeat(999)}</StepContent>
                    </Step>
                    <Step>
                        <StepLabel>Заберите результат</StepLabel>
                    </Step>
                </Stepper>
            </Container>
        </>
    )
}

export default Home
